import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-analysis',
  templateUrl: './analysis.component.html',
  styleUrls: ['./analysis.component.css']
})
export class AnalysisComponent implements OnInit {


  analysisTitle = "Analysis: Cluster Results";
  description = 'This page handles analysis of user data.';
  instructions = 'Text will be extracted from uploaded files and converted to word vector representations of entire emails. Those vectors are then fed to scikit learn, where they are clustered using the affinity propagation method. The visual output will be generated by matplotlib.';

  constructor() { }

  ngOnInit() {
  }

}
