import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-analysis',
  templateUrl: './analysis.component.html',
  styleUrls: ['./analysis.component.css']
})
export class AnalysisComponent implements OnInit {


  analysisTitle = "Analysis: Cluster Results";
  description = 'This app can be used to cluster text documents based on their content using an affinity propagation method.';
  instructions = 'Text will be extracted from uploaded files and converted to word vector representations. Those vectors are then fed to scikit learn, where they are clustered. The output is generated by matplotlib.';

  constructor() { }

  ngOnInit() {
  }

}
